import { db } from "./db";
import { activityLogTable } from "@workspace/db/schema";

export type ActivityType =
  | "attack_sent"
  | "attack_received"
  | "crime_success"
  | "crime_failed"
  | "jailed"
  | "released"
  | "joined_gang"
  | "left_gang"
  | "bodyguard_hired"
  | "black_market_listed"
  | "black_market_sale"
  | "black_market_purchase"
  | "traveled"
  | "arrived"
  | "attack_won"
  | "attack_lost"
  | "attack_repelled"
  | "attack_defended"
  | "guard_dismissed"
  | "attack_cancelled"
  | "rank_upgrade"
  | "property_purchased"
  | "property_upgraded"
  | "income_collected"
  | "killed"
  | "restart"
  | "anti_spy_purchased"
  | "reactor_built"
  | "reactor_constructed"
  | "reactor_collected"
  | "reactor_damaged"
  | "reactor_meltdown"
  | "bank_deposit"
  | "bank_withdraw"
  | "bank_interest"
  | "bank_loan_taken"
  | "bank_loan_repaid"
  | "bank_loan_garnished"
  | "bank_loan_seized"
  | "safe_house_rented"
  | "safe_house_collected"
  | "rank_promoted"
  | "supreme_fortress_built"
  | "casino_play"
  | "casino_win"
  | "casino_lose";

export async function logActivity(playerId: number, type: ActivityType, description: string) {
  await db.insert(activityLogTable).values({ playerId, type, description });
}
