export const REACTOR = {
  ENERGY_PER_HOUR: 100,
  ENERGY_CAP: 2400,
  MONEY_PER_ENERGY: 5000,
  CONSTRUCTION_HOURS: 168,
  INTEGRITY_DAMAGE_PER_HIT: 5,
  MELTDOWN_FEE: 10_000_000,
  MAX_CATCHUP_HOURS: 48,
} as const;

export function reactorIncomePerHour(): number {
  return REACTOR.ENERGY_PER_HOUR * REACTOR.MONEY_PER_ENERGY;
}
